name: Test quickssm

on:
  push:
    branches: [ main, 'feature/*', 'feat/*', 'issue/*' ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Install shellcheck
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update && sudo apt-get install -y shellcheck
        else
          brew install shellcheck
        fi
      shell: bash

    - name: Run shellcheck
      run: shellcheck -x authaws ssm src/*.sh

  # Enforce that PRs to main can only come from branches starting with "issues"
  branch-protection:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    
    steps:
    - name: Check branch name
      run: |
        if [[ ! "${{ github.head_ref }}" =~ ^issue ]]; then
          echo "❌ Pull requests to main branch must come from branches starting with 'issues'"
          echo "Current branch: ${{ github.head_ref }}"
          echo "Please create your PR from a branch that starts with 'issues/' (e.g., issues/123-fix-bug)"
          exit 1
        else
          echo "✅ Branch name is valid: ${{ github.head_ref }}"
        fi